apiVersion: v1
kind: Pod
metadata:
  name: dreg 
  labels:
    app: dreg
spec:
  volumes:
    - name: dreg-storage
      persistentVolumeClaim:
       claimName: dreg-pvc
  containers:
    - name: dreg
      image: registry:2
      args: ["/var/lib/registry/config.yml"]
      volumeMounts:
      - mountPath: "/var/lib/registry"
        name: dreg-storage
      ports:
      - containerPort: 5000
