kind: PersistentVolume
apiVersion: v1
metadata:
  name: exampleup-registry-pv
  labels:
    id: "exampleup-registry"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
