apiVersion: v1
kind: Service
metadata:
  name: example-2-svc 
spec:
  selector:
    app: example-2
  ports:
    - protocol: TCP
      port: 33001
      name: "editor"
    - protocol: TCP
      port: 33002
      name: "proxy"
  type: NodePort
